%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Politechnika\4 sem\MN\Project_1_MN\Crude Oil WTI Futures Historical Data.csv
%
% Auto-generated by MATLAB on 27-Mar-2023 12:27:56

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Date", "Price", "Open", "High", "Low", "Vol", "Change"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Vol", "Change"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Vol", "Change"], "ThousandsSeparator", ",");

% Import the data
CrudeOilWTIFuturesHistoricalData = readtable("C:\Politechnika\4 sem\MN\Project_1_MN\Crude Oil WTI Futures Historical Data.csv", opts);


%% Clear temporary variables
clear opts